require 'rubygems'
require 'rake/clean'
require_relative '../lib/nodenv/wrapper'

task default: ['nodenv']

desc "Install nodenv"
task :nodenv do
  sh "git clone https://github.com/nodenv/nodenv || /bin/true"
  sh "git clone https://github.com/nodenv/node-build nodenv/plugins/node-build || /bin/true"
  ENV['NODENV_ROOT'] = ENV['NODENV_DIR'] = "#{File.dirname(__FILE__)}/nodenv"
  sh "#{File.dirname(__FILE__)}/nodenv/bin/nodenv install -f #{Nodenv::Wrapper::NODE_VERSION}"
  IO.write('nodenv/version', Nodenv::Wrapper::NODE_VERSION)
end
