require 'rubygems'
require 'rake/clean'

task default: ['nodenv']

NODENV_VERSION = '8.6.0'

desc "Install nodenv"
task :nodenv do
  sh "[ -d nodenv ] || git clone https://github.com/nodenv/nodenv"
  sh "[ -d nodenv/plugins/node-build ] || git clone https://github.com/nodenv/node-build nodenv/plugins/node-build"
  ENV['NODENV_ROOT'] = ENV['NODENV_DIR'] = "#{File.dirname(__FILE__)}/nodenv"
  sh "[ -d nodenv/versions/#{NODENV_VERSION} ] || #{File.dirname(__FILE__)}/nodenv/bin/nodenv install #{NODENV_VERSION}"
  IO.write('nodenv/version', NODENV_VERSION)
end
